url: https://video.blondieandkangaroo.com
baseurl: 

# Site settings
title: Blondie&Kangaroo Video Portfolio
email: blondieandkangaroo@gmail.com
description: "Welcome to my mobile video portfolio page. More information inside!"


# Team names, titles and social links
people:
- name: Kangaroo
  pic: 1
  position: Kangaroo
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/blondieandkangaroo
  - title: facebook
    url: https://www.facebook.com/Blondie-Kangaroo-1860921794148161

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Build settings
markdown: kramdown
permalink: pretty